# permissions for end users to edit mypods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mypod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: duckdemo
    app.kubernetes.io/part-of: duckdemo
    app.kubernetes.io/managed-by: kustomize
  name: mypod-editor-role
rules:
- apiGroups:
  - core.duck.dev
  resources:
  - mypods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.duck.dev
  resources:
  - mypods/status
  verbs:
  - get
