---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.duck.dev
  resources:
  - mypods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.duck.dev
  resources:
  - mypods/finalizers
  verbs:
  - update
- apiGroups:
  - core.duck.dev
  resources:
  - mypods/status
  verbs:
  - get
  - patch
  - update
